from dataclasses import dataclass
from os.path import basename
from pathlib import Path
from typing import Annotated

import cappa
import numpy as np
from cellpose.io import logger_setup
from cellpose.models import CellposeModel
from cellpose.train import train_seg
from h5py import Dataset
from h5py import File as H5File
from h5py import Group


@dataclass
class ModelFromPath:
    path: Path


@dataclass
class ModelFromType:
    type: str


@dataclass
class RetrainConf:
    train_file: Annotated[Path, cappa.Arg(short="-i", help="path to input training file, generated by addlab.py")]
    out_path: Annotated[Path, cappa.Arg(short="-o", help="path to re-trained cellpose output weights file")]
    model_source: Annotated[
        ModelFromPath | ModelFromType,
        cappa.Arg(
            short="-m",
            help="name of pre-trained cellpose model to use. example: 'cyto3'",
            parse=lambda a: ModelFromType(type=a),
            group=cappa.Group(name="model source", exclusive=True),
        ),
        cappa.Arg(
            short="-w",
            help="path to cellpose model weights to use",
            parse=lambda a: ModelFromPath(Path(a)),
            group=cappa.Group(name="model source", exclusive=True),
        ),
    ]
    n_epochs: Annotated[int, cappa.Arg(short="-n", help="number of epochs for training")] = 300


def get_ds(grp: Group, key: str) -> np.ndarray:
    o = grp[key]
    if not isinstance(o, Dataset):
        raise ValueError(f"expected key {key} for group {grp} to be dataset, got {o}")
    return o[:]


def run_retrain(conf: RetrainConf):
    if isinstance(conf.model_source, ModelFromPath):
        model = CellposeModel(gpu=True, pretrained_model=str(conf.model_source.path))  # pyright: ignore
    else:
        model = CellposeModel(gpu=True, model_type=conf.model_source.type)

    with H5File(conf.train_file, "r") as hf:
        samples = [grp for grp in hf.values() if isinstance(grp, Group) and "labels" in grp]

        if not len(set(len(grp.keys()) for grp in samples)) == 1:
            raise ValueError(f"expected all samples in train file to be of same configuration, got: {samples}")

        nuc_seg = "channel: nuclear" in samples[0].keys()

        images = (
            [
                np.stack([get_ds(sample, "channel: segmentation"), get_ds(sample, "channel: nuclear")], axis=-1)
                for sample in samples
            ]
            if nuc_seg
            else [get_ds(sample, "channel: segmentation") for sample in samples]
        )

        labels = [get_ds(sample, "labels") for sample in samples]

    train_seg(
        model.net,
        train_data=images,
        train_labels=labels,
        channels=[1, 2] if nuc_seg else [0, 0],
        channel_axis=-1 if nuc_seg else None,
        normalize=True,
        weight_decay=1e-4,
        SGD=True,
        learning_rate=0.1,
        n_epochs=conf.n_epochs,
        save_path=conf.out_path,
    )


def run():

    conf = cappa.parse(cappa.Command(RetrainConf, name=basename(__file__)), completion=False)
    print(f"config: {conf}", flush=True)

    logger_setup()

    run_retrain(conf)


if __name__ == "__main__":
    run()
